### ISSUE TITLE
No progress shown when network is slow

### ISSUE THREAD

**Issue by mrienstra** [mskelton/yarn-plugin-outdated#11]
Using a slow network connection (but not terrible, between 3-8 Mbps down, 0.75-1 Mbps up), with 29 devDependencies & 4 dependencies, I measured a wait time of 30 seconds with no visual indication of progress.

Consider something to let the user know Things Are Happening™. Could be very simple, or a package like https://www.npmjs.com/package/cli-progress

**Comment by mskelton** [comment]
Great idea, I'll try to add this at some point when I have some free time.

**Comment by mskelton** [comment]
Made some progress on this today.  Just want you to know I am planning on finishing this, I've just been pretty busy lately!

**Comment by mrienstra** [comment]
Just gave it a try, very nice, thanks @mskelton!!! 👍👍

![yarn_outdated_progress_v1 1 0](https://user-images.githubusercontent.com/669326/124369710-b85cfd00-dc23-11eb-8517-1cdd0be1afa4.gif)
