### ISSUE TITLE
Bring back URLs

### ISSUE THREAD

**Issue by Shinigami92** [mskelton/yarn-plugin-outdated#16]
# Bring back URLs

These were really helpful cause I often jump in some of the URLs to look for changelogs

(These are screenshot from two different projects)

## Yarn v1:

<img src="https://user-images.githubusercontent.com/7195563/127831239-df6f0949-5116-4080-a309-b5baf5c2152e.png" width="600px"/>

## Yarn berry:

<img src="https://user-images.githubusercontent.com/7195563/127831277-bf658c19-94c6-4d84-b27b-957dfd9c3ad7.png" width="600px"/>

**Comment by mskelton** [comment]
I could see this being valuable.  One reason I didn't add them was due to the extra network requests to fetch them.  Thoughts about adding them behind a flag?  e.g.

```sh
yarn outdated --url
```

**Comment by Shinigami92** [comment]
> Thoughts about adding them behind a flag? e.g.
> 
> ```sh
> yarn outdated --url
> ```

Sure 👍

**Comment by Shinigami92** [comment]
Thanks, it works
But you should update the README.md 🙂

**Comment by mskelton** [comment]
> But you should update the README.md 🙂

Good reminder.  Updated!
