### ISSUE TITLE
Plugin not found after update

### ISSUE THREAD

**Issue by durchanek** [mskelton/yarn-plugin-outdated#31]
After updating to the most recent version, the plugin no longer executes:
```
% yarn outdated   
Usage Error: Couldn't find a script named "outdated".
```
I am using Yarn 2 - not sure if it may be connected.

**Comment by mskelton** [comment]
Version 2+ of this plugin is only compatible with Yarn 3.  I'd recommend updating your project to Yarn 3 to continue using the new features.

```sh
yarn set version latest
```
