### ISSUE TITLE
Ignore dependencies that use Protocols

### ISSUE THREAD

**Issue by rtritto** [mskelton/yarn-plugin-outdated#32]
With latest version [2.1.0](https://github.com/mskelton/yarn-plugin-outdated/releases/tag/v2.1.0) of `yarn-plugin-outdated`, _all_ dependencies in `yarn.lock` file are checked for outdated version.
Dependencies, that use [Protocols](https://yarnpkg.com/features/protocols) with `:` separator, should be ignored.
Some examples  (they need checks):
- `npm:<string>`
- `git@github.com:<string>`
- `github:<string>`
- `file:<string>`
- `link:<string>`
- `patch:<string>`
- `portal:<string>`
- `workspace:<string>`
- `exec:<string>`

# Steps to reproduce:
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn plugin import https://github.com/mskelton/yarn-plugin-outdated/raw/v2.1.0/bundles/@yarnpkg/plugin-outdated.js`
4. Add absolute path resolution with _link_ protocol:
`yarn add src@link:./src`
5. `yarn outdated`

# Results

## Actual
yarn log:
```
➤ YN0000: ┌ Checking for outdated dependencies
➤ YN0000: └ Completed

➤ YN0000: Package   Current   Latest   Package Type
➤ YN0000: src       0.0.0     1.1.2    dependencies

➤ YN0000: 1 dependency is out of date
➤ YN0000: Done with warnings in 0s 155ms
```

## Expect
No warnings.

**Comment by mskelton** [comment]
First of all, thanks for the detailed report!  I've setup a PR to ignore protocols except for the npm protocol as the latest version can be determined since we know the package name and version it is pointing to and can get the latest version from the registry.
