### ISSUE TITLE
Is there a way i can get list of only major version updates

### ISSUE THREAD

**Issue by mskelton** [mskelton/yarn-plugin-outdated#37]
Is there a way i can get list of only outdated dependencies.

_Originally posted by @Deepak7985 in https://github.com/yarnpkg/berry/issues/749#issuecomment-929924901_

**Comment by mskelton** [comment]
@Deepak7985 could you explain what you mean?  Do you mean a flag to ignore dev dependencies?

**Comment by Deepak7985** [comment]
i want count of those dependencies which are red in color, major update has been released.

**Comment by mskelton** [comment]
I'm thinking something like this could work.

```sh
yarn outdated --filter=major
```

Reason for that is it could be used for many use cases.

```sh
yarn outdated --filter=minor
yarn outdated --filter=major,minor
yarn outdated --filter=dependencies,major
```

Thoughts?

**Comment by Deepak7985** [comment]
no help , not even mentioned in the doc. I am wondering how does yarn color code it ? that might help

**Comment by mskelton** [comment]
@Deepak7985 What I posted is not available yet, it was a proposal of what the logic **could** be.  The color coding is handled by this plugin, not by Yarn itself.

The color value determination is handled here:

https://github.com/mskelton/yarn-plugin-outdated/blob/0f4ec0086e65e593a657849f70df5ac905aef8d6/src/DependencyTable.ts#L83-L92

**Comment by Deepak7985** [comment]
@mskelton there is a package whose major is same in current and latest but still shown in red color by yarn , package -> bundlesize2 , any idea ?

**Comment by mskelton** [comment]
Could you share a screenshot?

**Comment by Deepak7985** [comment]
<img width="1009" alt="Screenshot 2021-09-29 at 5 53 20 PM" src="https://user-images.githubusercontent.com/66246708/135267791-a763d023-bddc-4eca-b6ee-88480fc6c985.png">

**Comment by mskelton** [comment]
Okay, so two things here:

1. Looks like you are still using Yarn 1 whose outdated command is not this plugin.  This plugin is designed for Yarn 2 which doesn't provide outdated functionality out of the box.  Yarn 1 issues are filled here: https://github.com/yarnpkg/yarn/issues
2. The output for bundlesize2 is correct.  When a package is in version 0.x, minor version updates (e.g. 0.1.0 -> 0.2.0) are treated like major version changes as they may include breaking changes.

**Comment by joshuapinter** [comment]
@mskelton Are you still interested in something like this? If so, I think we can make time to create a PR for it.

**Comment by mskelton** [comment]
@joshuapinter This is already implemented using the `--severity` flag.

https://github.com/mskelton/yarn-plugin-outdated#filter-by-severity---severity--s

```
yarn outdated --severity=major
```

**Comment by joshuapinter** [comment]
Oh damn! Thanks for letting me know! 

I was wondering why it was available but it turns out I was still using the backed-in version of `yarn outdated` and hadn't actually installed the `outdated` plugin. 

I did and immediately the new argument worked. Thanks again.
