### ISSUE TITLE
Should include dependencies with patch: protocol

### ISSUE THREAD

**Issue by alamothe** [mskelton/yarn-plugin-outdated#42]
Hello, thank you for writing this very useful plugin!

Currently, it skips dependencies with `patch:` protocol. Such dependencies are specified like this:
```
    "puppeteer": "patch:puppeteer@10.4.0#./patches/puppeteer+10.4.0.patch",
```
Patches are always applied to a specific version. 

However, even though I applied a patch, I would still like to know if there is a new version of the dependency (perhaps they fixed the issue and my patch is no longer needed?). 

Thank you!

**Comment by mskelton** [comment]
Thanks for the report, wasn't sure if this was possible, but got a PR out to fix this!  Will release shortly!
