### ISSUE TITLE
Add a flag to include patch/minor dependency versions

### ISSUE THREAD

**Issue by ozsay** [mskelton/yarn-plugin-outdated#45]
Sometimes it is not possible to upgrade to latest (`semver` major may contain breaking changes).

So it is useful to see if any new patch/minor versions exist.

Thanks!

**Comment by mskelton** [comment]
The plugin already has a `--severity` option which you can use to filter by severity.  So,

```sh
yarn outdated --severity minor
```

would only show minor updates.  Though the plugin only supports specifying a single severity right now (e.g. `--severity=minor,patch` doesn't work) would this fulfill your use case?

**Comment by ozsay** [comment]
the severity filtering helps, but it's not 100% what I was looking for.

I pulled the repo and made a few changes locally.

the colors are a bit off, but if you check the values of `@babel/core` and `eslint`, you see what I'm really after

![](https://user-images.githubusercontent.com/3464930/154904647-003ac626-7129-4f4e-8272-57420f877af8.png)

**Comment by mskelton** [comment]
Interesting, that's not a use case I've thought of before.  What would you propose for CLI options to get this type of output?

**Comment by ozsay** [comment]
maybe "--full" ? "display full information about versions including minor/patch"?

**Comment by mskelton** [comment]
Hmm, my concern with that is:

1. To display patch, minor, and latest would triple the number of network requests when checking for outdated dependencies.
1. Adding the extra logic to fetch minor and patch versions which may further complicate the plugin for a more unusual use case.

**Comment by ozsay** [comment]
hey, I created a PR with some changes to the fetcher. it is now gets the versions directly from npm.

it fixes the multiple requests issue, but may not cover all cases?

everything else in the PR is a draft
