### ISSUE TITLE
Incorrect color mapping

### ISSUE THREAD

**Issue by Semigradsky** [mskelton/yarn-plugin-outdated#47]
![image](https://user-images.githubusercontent.com/1198848/155491633-e36aca96-eb3d-40c1-8439-408659d2e0d5.png)
[By semver](https://semver.org/#spec-item-4):
> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

So it should be red.

**Comment by mskelton** [comment]
Good catch, I'll put together a fix for this.

**Comment by mskelton** [comment]
Updated.  Until I release the next version, you can install from the main branch.

```sh
yarn plugin import https://mskelton.dev/yarn-outdated/main
```
