### ISSUE TITLE
[Feature request] URL column

### ISSUE THREAD

**Issue by Semigradsky** [mskelton/yarn-plugin-outdated#48]
Thanks for the cool plugin!

It would be nice to have an URL column. It is convenient to go to the library repository to check the CHANGELOG.
As far as I know, it was showing the `repository` field from `package.json`.

**Comment by mskelton** [comment]
Good news, this already exists!  Just add the `--url` flag.

```sh
yarn outdated --url
```

**Comment by Semigradsky** [comment]
Wow!
