### ISSUE TITLE
[Feature Request] Dependency repo url

### ISSUE THREAD

**Issue by ptfly** [mskelton/yarn-plugin-outdated#54]
Is it possible to have the repo URL, easier to click and change the release changelog? 
Thanks for the plugin, I'm really used to using it in yarn v1, now after migrating to v3 - very helpful!

Linking directly to `${repoUrl}/releases` might be even better :)

**Comment by mskelton** [comment]
This is already possible with the `--url` flag which will display the package homepage URL.

```sh
yarn outdated --url
```

**Comment by TheThirdRace** [comment]
@mskelton 

First, your plugin is simply awesome. I still can't believe `yarn` maintainers decided to drop this command... 

As for the topic at hand, having to write `--url` every time goes against years of muscle memory 😅 

`yarn classic` displays urls by default, but having to use `--url` is the total opposite. 

What could be done so we can simply type `yarn outdated` like we used to and get the result of `yarn outdated --url`?
- Is there a way to alias `yarn outdated --url` as `yarn outdated`?
- Is there a config file?
- Change the default to display url and have a `--no-url` flag instead?
