### ISSUE TITLE
URL by default

### ISSUE THREAD

**Issue by mskelton** [mskelton/yarn-plugin-outdated#75]
First, your plugin is simply awesome. I still can't believe `yarn` maintainers decided to drop this command... 

As for the topic at hand, having to write `--url` every time goes against years of muscle memory 😅 

`yarn classic` displays urls by default, but having to use `--url` is the total opposite. 

What could be done so we can simply type `yarn outdated` like we used to and get the result of `yarn outdated --url`?
- Is there a way to alias `yarn outdated --url` as `yarn outdated`?
- Is there a config file?
- Change the default to display url and have a `--no-url` flag instead?

_Originally posted by @TheThirdRace in https://github.com/mskelton/yarn-plugin-outdated/issues/54#issuecomment-1328282989_

**Comment by mskelton** [comment]
@TheThirdRace I am not interested in changing the default as fetching the URL requires additional network requests and keeping this plugin as light as possible is important for me to ensure it can, by default, run as fast as possible.

That said, I think a config file item to set some defaults would be a great solution to fulfill your use case.

**Comment by inferusvv** [comment]
Oh, also interested in it. Maybe someone knows is there any possibility to set it enabled by default in project? For example in `.yarnrc.yml` or something like that..

**Comment by mskelton** [comment]
It's not possible yet, but I plan to eventually implement it.

**Comment by mskelton** [comment]
This is now available in version 3.2.0

https://github.com/mskelton/yarn-plugin-outdated/tree/v3.2.0#configuration
