### ISSUE TITLE
Is mskelton.dev down?

### ISSUE THREAD

**Issue by dtarnawsky** [mskelton/yarn-plugin-outdated#86]
When running:
yarn plugin import https://mskelton.dev/yarn-outdated/v4

it is freezing at:
➤ YN0000: Downloading https://mskelton.dev/yarn-outdated/v4

**Comment by mskelton** [comment]
This is fixed now

**Comment by rgilsimoes** [comment]
Working now!

**Comment by mskelton** [comment]
@dtarnawsky That's awesome to hear!
