### ISSUE TITLE
publish plugin to npm

### ISSUE THREAD

**Issue by ccdd13** [mskelton/yarn-plugin-outdated#9]
Hi,
plugin not in npmjs.com

**Comment by mskelton** [comment]
Hi @ccdd13,

Yarn plugins aren't published to npm but are installed from a bundle URL.  The installation instructions in the readme explain how to import this plugin like so:

```sh
yarn plugin import https://github.com/mskelton/yarn-plugin-outdated/raw/main/bundles/@yarnpkg/plugin-outdated.js
```

After running that, commit the resulting changes to the `.yarn` folder and the `.yarnrc.yml` file.
